version: '3.9'

networks:
  traefik_savla:
    name: ${DOCKER_NETWORK_NAME}
    external: true

volumes:
  litter-data:
    name: "litter-data"
  litter-pix:
    name: "litter-pix"

services:
  litter-backend:
    image: ${DOCKER_IMAGE_TAG}
    container_name: ${DOCKER_CONTAINER_NAME}
    env_file:
      - ../.env
    build:
      context: ..
      dockerfile: deployments/Dockerfile
      args: 
        APP_NAME: ${APP_NAME}
        APP_FLAGS: ${APP_FLAGS}
        APP_PEPPER: ${APP_PEPPER}
        APP_VERSION: ${APP_VERSION}
        DOCKER_INTERNAL_PORT: ${DOCKER_INTERNAL_PORT} 
        DOCKER_USER: ${DOCKER_USER}
        GOCACHE: ${GOCACHE}
        GOMODCACHE: ${GOMODCACHE}
        GOLANG_VERSION: ${GOLANG_VERSION}
        TZ: ${TZ}
        VAPID_PUB_KEY: ${VAPID_PUB_KEY}
    restart: unless-stopped
    cpus: 0.3
    mem_limit: 128m
    mem_reservation: 32m
    volumes:
      - "litter-data:/opt/data"
      - "litter-pix:/opt/pix"
    ports:
      - "${DOCKER_EXTERNAL_PORT}:${DOCKER_INTERNAL_PORT}"
    networks:
      - ${DOCKER_NETWORK_NAME}
    labels:
      - "traefik.http.routers.${APP_NAME}.rule=Host(${APP_URLS_TRAEFIK})"
      - "traefik.http.services.${APP_NAME}.loadbalancer.server.port=${DOCKER_INTERNAL_PORT}"
      - "traefik.docker.network=${DOCKER_NETWORK_NAME}"
    environment:
      API_TOKEN: ${API_TOKEN}
      APP_PEPPER: ${APP_PEPPER}
      VAPID_PUB_KEY: ${VAPID_PUB_KEY}
    healthcheck:
      #test: ["CMD", "/opt/periodic-dump.sh"]
      test: ["CMD", "wget", "--header", "X-Dump-Token: ${API_TOKEN}", "localhost:${DOCKER_INTERNAL_PORT}/api/v1/dump", "-O", "-", "-S" ]
      interval: 5m
      timeout: 5s
      retries: 3

  litter-swagger:
    image: swaggerapi/swagger-ui
    container_name: litter-swagger
    ports: 
      - target: 8080
        published: 8998
        mode: host
        protocol: tcp
    environment: 
      BASE_URL: "/docs/"
      BASE_PATH: "/api"
      SWAGGER_JSON: "/tmp/swagger.json"
    networks: 
      - ${DOCKER_NETWORK_NAME}
    volumes: 
      - "./docs/swagger.json:/tmp/swagger.json"
    labels:
      - "traefik.http.routers.${APP_NAME}-swagger.rule=Host(${APP_URLS_TRAEFIK}) && PathPrefix(`/docs`)"
      - "traefik.http.services.${APP_NAME}-swagger.loadbalancer.server.port=8080"
      #- "traefik.http.middlewares.${APP_NAME}.stripprefix.prefixes=/docs"
      - "traefik.docker.network=${DOCKER_NETWORK_NAME}"

