# littr Gitlab CI configuration file

workflow:
  rules: 
    - if: '$CI_COMMIT_TAG'
      when: always
    - when: never

stages:         
  - build
  - deploy

build-image:  
  stage: build
  rules:
    - if: $APP_PEPPER != null
    - if: $DOCKER_CONTAINER_NAME != null
    - if: $DOCKER_NETWORK_NAME != null
    - if: $VAPID_PUBLIC_KEY != null
  variables:
    APP_VERSION: $CI_COMMIT_TAG
  script:
    - make build
    - make push_to_registry

deploy-stage:    
  stage: deploy
  environment: 
    name: stage
  needs:
    - build-image
  when: manual
  script:
    - echo "Deploying application..."
    - echo "Application successfully deployed."

deploy-prod: 
  stage: deploy
  environment: 
    name: prod
  needs:
    - build-image
  when: manual
  script:
    - echo "Deploying application..."
    - echo "Application successfully deployed."
