# littr Gitlab CI configuration file

workflow:
  rules: 
    - if: '$CI_COMMIT_TAG'
      when: always
    - when: never

stages:         
  - build
  - deploy

build-image:  
  stage: build
  rules:
    - if: $APP_PEPPER != null
    - if: $VAPID_PUBLIC_KEY != null
  variables:
    APP_VERSION: $CI_COMMIT_TAG
  script:
    - make build
    - make push_to_registry

deploy-stage:    
  stage: deploy
  environment: 
    name: stage
  when: manual
  variables:
    APP_ENVIRONMENT: $CI_JOB_STAGE
  before_script:
    - eval $(ssh-agent -s)
    - chmod 400 "$DEPLOY_SSH_KEY"
    - ssh-add "$DEPLOY_SSH_KEY"
  script:
    - export DOCKER_HOST=ssh://$DEPLOY_USER@$DEPLOY_TARGET
    - make run

deploy-prod: 
  stage: deploy
  environment: 
    name: prod
  when: manual
  variables:
    APP_ENVIRONMENT: $CI_JOB_STAGE
  before_script:
    - eval $(ssh-agent -s)
    - chmod 400 "$DEPLOY_SSH_KEY"
    - ssh-add "$DEPLOY_SSH_KEY"
  script:
    - export DOCKER_HOST=ssh://$DEPLOY_USER@$DEPLOY_TARGET
    - make run

