# littr Gitlab CI configuration file

workflow:
  rules: 
    - if: '$CI_COMMIT_TAG'
      when: always
    - when: never

stages:         
  - build
  - deploy

build-image:  
  stage: build
  rules:
    - if: $APP_PEPPER != null
    - if: $VAPID_PUBLIC_KEY != null
  variables:
    APP_VERSION: $CI_COMMIT_TAG
  script:
    - make build
    - make push_to_registry

deploy-stage:    
  stage: deploy
  environment: 
    name: stage
  needs:
    - build-image
  when: manual
  script:
    - echo "Deploying application..."
    - echo "Application successfully deployed."

deploy-prod: 
  stage: deploy
  environment: 
    name: prod
  needs:
    - build-image
  when: manual
  variable:
    APP_ENVIRONMENT: $CI_JOB_STAGE
  before_script:
    - chmod 400 "$DOCKER_SSH_KEY"
    - ssh-add "$DOCKER_SSH_KEY"
  script:
    - export DOCKER_HOST=ssh://docker@$DEPLOY_TARGET
    - make run

