version: '3.9'

networks:
  traefik_savla:
    name: ${DOCKER_NETWORK_NAME}
    external: true

volumes:
  litter-data:
    name: "litter-data"
  litter-pix:
    name: "litter-pix"

services:
  litter-backend:
    image: ${DOCKER_IMAGE_TAG}
    container_name: ${DOCKER_CONTAINER_NAME}
    env_file:
      - .env
    build:
      context: .
      args: 
        APP_NAME: ${APP_NAME}
        APP_FLAGS: ${APP_FLAGS}
        APP_PEPPER: ${APP_PEPPER}
        APP_VERSION: ${APP_VERSION}
        API_TOKEN: ${API_TOKEN}
        DOCKER_INTERNAL_PORT: ${DOCKER_INTERNAL_PORT} 
        DOCKER_USER: ${DOCKER_USER}
        GOLANG_VERSION: ${GOLANG_VERSION}
        TZ: ${TZ}
    restart: unless-stopped
    cpus: 0.3
    mem_reservation: 128m
    volumes:
      - "litter-data:/opt/data"
      - "litter-pix:/opt/pix"
    ports:
      - "${DOCKER_EXTERNAL_PORT}:${DOCKER_INTERNAL_PORT}"
    networks:
      - ${DOCKER_NETWORK_NAME}
    labels:
      - "traefik.http.routers.${APP_NAME}.rule=Host(${APP_URLS_TRAEFIK})"
      - "traefik.http.services.${APP_NAME}.loadbalancer.server.port=${DOCKER_INTERNAL_PORT}"
      - "traefik.docker.network=${DOCKER_NETWORK_NAME}"
    #healthcheck:
      #test: ["CMD", "/opt/periodic-dump.sh"]
      #interval: 15m
      #timeout: 5s
      #retries: 1

