version: '3.9'

networks:
  traefik_savla:
    name: ${DOCKER_NETWORK_NAME}

services:
  litter-backend:
    image: ${DOCKER_IMAGE_TAG}
    container_name: ${DOCKER_CONTAINER_NAME}
    env_file:
      - .env
    build:
      context: .
      args: 
        APP_NAME: ${APP_NAME}
        APP_FLAGS: ${APP_FLAGS}
        DOCKER_INTERNAL_PORT: ${DOCKER_INTERNAL_PORT} 
        DOCKER_USER: ${DOCKER_USER}
        GOLANG_VERSION: ${GOLANG_VERSION}
        TZ: ${TZ}
    restart: unless-stopped
    cpus: 0.3
    mem_reservation: 128m
    #environment:
    ports:
      - "${DOCKER_EXTERNAL_PORT}:${DOCKER_INTERNAL_PORT}"
    networks:
      - ${DOCKER_NETWORK_NAME}
    labels:
      - "traefik.http.routers.${APP_NAME}.rule=Host(${APP_URLS_TRAEFIK})"
      - "traefik.http.services.${APP_NAME}.loadbalancer.server.port=${DOCKER_INTERNAL_PORT}"
      - "traefik.docker.network=${DOCKER_NETWORK_NAME}"

